version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financial-control
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: